apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
---
# Similarly you can use a ClusterRole and ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin-role
rules:
  - apiGroups:
      - argoproj.io
    verbs:
      - "*"
    resources:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin-role
subjects:
  - kind: ServiceAccount
    name: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: admin.service-account-token
  annotations:
    kubernetes.io/service-account.name: admin
type: kubernetes.io/service-account-token
